site_name: BeefPotato Docs
nav:
  - Home: index.md
  - About: about.md
  - Notes:
      - mkdocs搭建网站.md
      - pwshBonus.md
      - galgameTools.md
      - test.md
      - 如何关闭windows defender.md
      - 荧光文字倒影.md
      - spine2spritesheet.md
      - mkdocsWithLive2d.md
theme: material
extra_javascript:
  - javascripts/live2d.js