site_name: BeefPotato Docs
nav:
  - Home: index.md
  - About: about.md
  - Notes:
      - mkdocs 自动添加yml文件.md
      - 推荐阅读.md
      - 强力对策平衡.md
      - 密码管理软件.md
      - baiduAPI+xunity_autotranslator.md
      - mkdocs搭建网站.md
      - pwshBonus.md
      - galgameTools.md
      - 如何关闭windows defender.md
      - 荧光文字倒影.md
      - spine2spritesheet.md
      - mkdocsWithLive2d.md
      - MusicFree依赖安装.md
      - 杂项.md
      - elf 汉化记录.md
  - 杂项:
      - 尼普顿空调租赁.md
  - 测试:
      - test.md
theme: 
    name: material
    features:
        - content.code.copy
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
